### PR TITLE
Updated yaml rust, fixed tests

### PR DESCRIPTION
**Pull request by ms-chrmiller**
`yaml-rust` was broken for newer versions of rustc (tested on 1.60), leading to

```
thread 'main' panicked at 'attempted to leave type `linked_hash_map::Node<yaml::Yaml, yaml::Yaml>` uninitialized, which is invalid', /Users/[user]/.cargo/registry/src/github.com-1ecc6299db9ec823/linked-hash-map-0.5.2/src/lib.rs:174:52
```

when loading `config.yml`

This PR is a simple version bump to fix the error.

Additionally, there were two tests failing to an unrelated string formatting issue. I updated them to match.

### CODE REVIEW

**Review by artem-zinnatullin — APPROVED** [review]

**Comment by artem-zinnatullin** [comment]
Thanks, looks good! 

Btw, did you mean to commit from https://github.com/ChristopherJMiller by chance? I'll give it a few days before merge so you could re-open PR or push amended commit (but I think GitHub will still link PR to the user that opened PR rather than the authors of the commit).

Sorry, had to look up the profile and couldn't help but notice that the only public contribution from @ms-chrmiller is this PR 😅

Was trying to double-check that this PR is not doing some sort of dependency update hack pointing the build to malicious dependencies as it was recently done with [NPM packages](https://arstechnica.com/information-technology/2021/12/malicious-packages-sneaked-into-npm-repository-stole-discord-tokens/) and some other — can't find the link

**Comment by ms-chrmiller** [comment]
Hello!

I was originally going to do it from my personal account `ChristopherJMiller` but I was contributing on company hours so to be safe I did it from a new work account 😅 sorry for the scare, this can be merged 

I appreciate the caution given the threat of dependency attacks out there

**Comment by artem-zinnatullin** [comment]
Got it, merging then, thanks for PR!!

Btw, if you want to take some tasks on the Rust version of Mainframer — I'd be happy to accept contributions and participate in discussions and even promote you to maintainers of the repo if contributions become consistent :)

Seems like Travis CI Integration died (prob expired), going to convert CI to GitHub Actions today-tomorrow.

**Comment by ms-chrmiller** [comment]
Sounds good thank you!

You'll probably see some PRs from @akshob and I over the next little bit :) excited to be able to contribute to something open source.

What would be the best way to open discussions about topic? Something that comes to mind immediately is some of your config parsing logic could be simplified/eliminated with the aid of something like [serde](https://serde.rs)

**Comment by artem-zinnatullin** [comment]
>You'll probably see some PRs from @akshob and I over the next little bit :) excited to be able to contribute to something open source.

👍 

>What would be the best way to open discussions about topic? Something that comes to mind immediately is some of your config parsing logic could be simplified/eliminated with the aid of something like [serde](https://serde.rs/)

Just open an issue with brief explanation and we'll discuss it there, for example the `serde` change :)

If it's something trivial like dependency update or code smell fix — PR without and separate issue would be totally fine like this one

**Pull request merged**
