### PR TITLE
Add note about battery life improvements.

### PR DESCRIPTION
**Pull request by artem-zinnatullin**
I think it's very important point, I'm able to work in the office kitchen for half of the day now 😸

### CODE REVIEW

**Review by arturdryomov — COMMENTED** [review]
STOP IT

**Comment by artem-zinnatullin** [comment]
Marketing, do you speak it!

**Comment by arturdryomov** [comment]
We’ve spent so much time making disclaimer shorter to include more marketing? Ugh.

**Comment by artem-zinnatullin** [comment]
giphy-facebook_s

**Comment by artem-zinnatullin** [comment]
Let's do it

**Comment by artem-zinnatullin** [comment]
I'm slowly pressing `Squash and merge`…

**Comment by arturdryomov** [comment]
DO NOT WANT. Too much useless text.

**Comment by artem-zinnatullin** [comment]
driving_me_nuts

**Comment by artem-zinnatullin** [comment]
Actually, I think it's very major point.

**Comment by arturdryomov** [comment]
Still not convinced. CC @dmitry-novikov

**Comment by dmitry-novikov** [comment]
Agree with @ming13.

**Comment by artem-zinnatullin** [comment]
Uh.

**Pull request closed without merging**
