### PR TITLE
Leftwards arrow in syncAfterBuild message.

### PR DESCRIPTION
**Pull request by artem-zinnatullin**

### CODE REVIEW

**Review by arturdryomov — CHANGES_REQUESTED** [review]
Nope. Are you Yoda or something?

**Comment by artem-zinnatullin** [comment]
I just want to be able to quickly understand what the state is by looking on logs without reading words.

**Comment by arturdryomov** [comment]
It is pretty hard to understand this when you read the text.

**Comment by artem-zinnatullin** [comment]
Ok, let's close it for now.

**Pull request closed without merging**
