### PR TITLE
Use fixed version of Rust (1.24.0) instead of latest stable.

### PR DESCRIPTION
**Pull request by artem-zinnatullin**
Part of #193.

This makes our build much more predictable and reproducible.

### CODE REVIEW

**Comment by arturdryomov** [comment]
Nothing says safety better than running bash scripts from a web link.

**Review by arturdryomov — APPROVED** [review]

**Comment by artem-zinnatullin** [comment]
Hey, at least it's https lol, but that's recommended install way https://www.rust-lang.org/en-US/install.html

**Comment by artem-zinnatullin** [comment]
Btw, highly recommend to check code of https://static.rust-lang.org/rustup.sh

That's level of programming in Bash I can live with

**Comment by arturdryomov** [comment]
The script looks nice, but such size makes it kind of complex anyway ;-(

**Comment by artem-zinnatullin** [comment]
Well sure, but you probably don't want script to download its parts during execution

**Pull request merged**
