### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by meierjan**
added note for task pitfall

### CODE REVIEW

**Comment by meierjan** [comment]
I just wanted to point this out as this is a stupid pitfall for starters.

**Comment by artem-zinnatullin** [comment]
Ah damn, right right. We don't have flavors, so it didn't come up in our use case.

**Comment by artem-zinnatullin** [comment]
Merged as is, but we'll reword that in some future,  thanks!

**Comment by meierjan** [comment]
Of course. Thanks!

**Pull request merged**
