### PR TITLE
Add integration test for remote command stdout piping.

### PR DESCRIPTION
**Pull request by artem-zinnatullin**
Part of #205.

If this PR gets approved, I'll submit another one for stderr.

### CODE REVIEW

**Comment by arturdryomov** [comment]
And why do we need this test at all? You don’t trust SSH implementations?

**Comment by artem-zinnatullin** [comment]
Well, because we control if `ssh` output gets piped into Mainframer output or not and it's pretty easy to break during development.

**Comment by artem-zinnatullin** [comment]
Also, in future we might want to implement protocol `ssh` inside Mainframer

**Review by arturdryomov — APPROVED** [review]

**Comment by artem-zinnatullin** [comment]
Yeah, we should definitely move samples out of this repo:

(damn Bintray)

```console
* What went wrong:
A problem occurred configuring root project 'run'.
> Could not resolve all files for configuration ':classpath'.
   > Could not download gradle-core.jar (com.android.tools.build:gradle-core:2.2.3)
      > Could not get resource 'https://jcenter.bintray.com/com/android/tools/build/gradle-core/2.2.3/gradle-core-2.2.3.jar'.
         > Could not GET 'https://jcenter.bintray.com/com/android/tools/build/gradle-core/2.2.3/gradle-core-2.2.3.jar'.
            > Connect to akamai.bintray.com:443 [akamai.bintray.com/23.45.134.89] failed: Connection timed out (Connection timed out)
```

**Pull request merged**
