### PR TITLE
Use same dots symbols everywhere.

### PR DESCRIPTION
**Pull request by arturdryomov**

### CODE REVIEW

**Review by dmitry-novikov — APPROVED** [review]

**Review by artem-zinnatullin — CHANGES_REQUESTED** [review]
I've made real dots for a reason, not all terminal/OS combinations can display... properly :(

**Comment by arturdryomov** [comment]
@artem-zinnatullin, so which dots should we use everywhere? Regular or Unicode ones?

**Comment by artem-zinnatullin** [comment]
Regular I think, for instance (it's not the case with Mainframer though)
Jenkins can't display unicode variant properly and I have to use regular
dots in all CI related projects

**Comment by arturdryomov** [comment]
Done.

**Review by artem-zinnatullin — APPROVED** [review]

**Pull request merged**
